/**
 * Sample controller to demonstrate controller pattern
 */

// Get all items
const getAllItems = async (req, res) => {
  try {
    // This is where you would fetch data from your database
    const sampleData = [
      { id: 1, name: 'Item 1', description: 'Description for item 1' },
      { id: 2, name: 'Item 2', description: 'Description for item 2' },
    ];
    
    res.status(200).json({
      success: true,
      count: sampleData.length,
      data: sampleData
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Server Error',
      error: error.message
    });
  }
};

// Get single item
const getItemById = async (req, res) => {
  try {
    const id = parseInt(req.params.id);
    
    // This is where you would fetch a specific item from your database
    const item = { id, name: `Item ${id}`, description: `Description for item ${id}` };
    
    res.status(200).json({
      success: true,
      data: item
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Server Error',
      error: error.message
    });
  }
};

// Create new item
const createItem = async (req, res) => {
  try {
    const { name, description } = req.body;
    
    if (!name || !description) {
      return res.status(400).json({
        success: false,
        message: 'Please provide name and description'
      });
    }
    
    // This is where you would create a new item in your database
    const newItem = {
      id: 3, // In a real app, this would be generated by the database
      name,
      description
    };
    
    res.status(201).json({
      success: true,
      data: newItem
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Server Error',
      error: error.message
    });
  }
};

module.exports = {
  getAllItems,
  getItemById,
  createItem
};
